/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as CallcenterRouteImport } from './routes/callcenter'
import { Route as CookieEinstellungenRouteImport } from './routes/cookie-einstellungen'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KarriereRouteImport } from './routes/karriere'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as VorteileRouteImport } from './routes/vorteile'
import { Route as BranchenSlugRouteImport } from './routes/branchen.$slug'
import { Route as KarriereIndexRouteImport } from './routes/karriere.index'
import { Route as KarriereRecruitingRouteImport } from './routes/karriere.recruiting'
import { Route as KarriereSekretariatRouteImport } from './routes/karriere.sekretariat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const CallcenterRoute = CallcenterRouteImport.update({
  id: '/callcenter',
  path: '/callcenter',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieEinstellungenRoute = CookieEinstellungenRouteImport.update({
  id: '/cookie-einstellungen',
  path: '/cookie-einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereRoute = KarriereRouteImport.update({
  id: '/karriere',
  path: '/karriere',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const VorteileRoute = VorteileRouteImport.update({
  id: '/vorteile',
  path: '/vorteile',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchenSlugRoute = BranchenSlugRouteImport.update({
  id: '/branchen/$slug',
  path: '/branchen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereIndexRoute = KarriereIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KarriereRoute,
} as any)
const KarriereRecruitingRoute = KarriereRecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => KarriereRoute,
} as any)
const KarriereSekretariatRoute = KarriereSekretariatRouteImport.update({
  id: '/sekretariat',
  path: '/sekretariat',
  getParentRoute: () => KarriereRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/callcenter': typeof CallcenterRoute
  '/cookie-einstellungen': typeof CookieEinstellungenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/vorteile': typeof VorteileRoute
  '/branchen/$slug': typeof BranchenSlugRoute
  '/karriere/recruiting': typeof KarriereRecruitingRoute
  '/karriere/sekretariat': typeof KarriereSekretariatRoute
  '/karriere/': typeof KarriereIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/callcenter': typeof CallcenterRoute
  '/cookie-einstellungen': typeof CookieEinstellungenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/vorteile': typeof VorteileRoute
  '/branchen/$slug': typeof BranchenSlugRoute
  '/karriere/recruiting': typeof KarriereRecruitingRoute
  '/karriere/sekretariat': typeof KarriereSekretariatRoute
  '/karriere': typeof KarriereIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/callcenter': typeof CallcenterRoute
  '/cookie-einstellungen': typeof CookieEinstellungenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/preise': typeof PreiseRoute
  '/vorteile': typeof VorteileRoute
  '/branchen/$slug': typeof BranchenSlugRoute
  '/karriere/recruiting': typeof KarriereRecruitingRoute
  '/karriere/sekretariat': typeof KarriereSekretariatRoute
  '/karriere/': typeof KarriereIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/callcenter'
    | '/cookie-einstellungen'
    | '/datenschutz'
    | '/impressum'
    | '/karriere'
    | '/kontakt'
    | '/preise'
    | '/vorteile'
    | '/branchen/$slug'
    | '/karriere/recruiting'
    | '/karriere/sekretariat'
    | '/karriere/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/callcenter'
    | '/cookie-einstellungen'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/preise'
    | '/vorteile'
    | '/branchen/$slug'
    | '/karriere/recruiting'
    | '/karriere/sekretariat'
    | '/karriere'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/callcenter'
    | '/cookie-einstellungen'
    | '/datenschutz'
    | '/impressum'
    | '/karriere'
    | '/kontakt'
    | '/preise'
    | '/vorteile'
    | '/branchen/$slug'
    | '/karriere/recruiting'
    | '/karriere/sekretariat'
    | '/karriere/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  CallcenterRoute: typeof CallcenterRoute
  CookieEinstellungenRoute: typeof CookieEinstellungenRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KarriereRoute: typeof KarriereRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  PreiseRoute: typeof PreiseRoute
  VorteileRoute: typeof VorteileRoute
  BranchenSlugRoute: typeof BranchenSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callcenter': {
      id: '/callcenter'
      path: '/callcenter'
      fullPath: '/callcenter'
      preLoaderRoute: typeof CallcenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-einstellungen': {
      id: '/cookie-einstellungen'
      path: '/cookie-einstellungen'
      fullPath: '/cookie-einstellungen'
      preLoaderRoute: typeof CookieEinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere': {
      id: '/karriere'
      path: '/karriere'
      fullPath: '/karriere'
      preLoaderRoute: typeof KarriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vorteile': {
      id: '/vorteile'
      path: '/vorteile'
      fullPath: '/vorteile'
      preLoaderRoute: typeof VorteileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branchen/$slug': {
      id: '/branchen/$slug'
      path: '/branchen/$slug'
      fullPath: '/branchen/$slug'
      preLoaderRoute: typeof BranchenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/': {
      id: '/karriere/'
      path: '/'
      fullPath: '/karriere/'
      preLoaderRoute: typeof KarriereIndexRouteImport
      parentRoute: typeof KarriereRoute
    }
    '/karriere/recruiting': {
      id: '/karriere/recruiting'
      path: '/recruiting'
      fullPath: '/karriere/recruiting'
      preLoaderRoute: typeof KarriereRecruitingRouteImport
      parentRoute: typeof KarriereRoute
    }
    '/karriere/sekretariat': {
      id: '/karriere/sekretariat'
      path: '/sekretariat'
      fullPath: '/karriere/sekretariat'
      preLoaderRoute: typeof KarriereSekretariatRouteImport
      parentRoute: typeof KarriereRoute
    }
  }
}

interface KarriereRouteChildren {
  KarriereRecruitingRoute: typeof KarriereRecruitingRoute
  KarriereSekretariatRoute: typeof KarriereSekretariatRoute
  KarriereIndexRoute: typeof KarriereIndexRoute
}

const KarriereRouteChildren: KarriereRouteChildren = {
  KarriereRecruitingRoute: KarriereRecruitingRoute,
  KarriereSekretariatRoute: KarriereSekretariatRoute,
  KarriereIndexRoute: KarriereIndexRoute,
}

const KarriereRouteWithChildren = KarriereRoute._addFileChildren(
  KarriereRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  CallcenterRoute: CallcenterRoute,
  CookieEinstellungenRoute: CookieEinstellungenRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KarriereRoute: KarriereRouteWithChildren,
  KontaktRoute: KontaktRoute,
  PreiseRoute: PreiseRoute,
  VorteileRoute: VorteileRoute,
  BranchenSlugRoute: BranchenSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
